apiVersion: batch/v1
kind: Job
metadata:
  name: countdown-devops
spec:
  template:
    spec:
      containers:
      - name: container-countdown-devops
        image: centos:latest
        command: ["/bin/bash","-c", "for i in 10 9 8 7 6 5 4 3 2 1 ; do echo $i ; done"]
      restartPolicy: Never