apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name:  haproxy-cluster-role-binding-xfusion
  
subjects:
- kind: ServiceAccount
  name: haproxy-service-account-xfusion
  namespace: haproxy-controller-xfusion 
roleRef:
  kind: ClusterRole
  name: haproxy-cluster-role-xfusion
  apiGroup: rbac.authorization.k8s.io